### ISSUE TITLE
Write AssignCardToSender for GraphQL

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/gh-action-lt-backlog#41]
https://github.com/SonarSource/gh-action-lt-backlog/tree/master/AssignCardToSender

**Comment by ilia-kebets-sonarsource** [comment]
I can't find a trigger for this action, since the old one only works for `projects (classic)`: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#project_card

**Comment by pavel-mikula-sonarsource** [comment]
Not relevant anymore
